### PR TITLE
Add support for custom headers

### PR DESCRIPTION
**Pull request by realcoloride**
Hello!

Some services/backends require specific kinds of headers in order to function properly. This being a missing feature in other packages, I have opened a fork and have implemented the patch myself, and I need it also for a personal project.

I also took the time to modernize some of the code.

Now, anyone is able to specify their own custom headers.

```cs
websocket.Headers["x-super-cool-header"] = "Hello world!";
```

Cheers, and let me know if there are things to improve.

### CODE REVIEW

**Comment by kerryjiang** [comment]
I will do some optimizations around it later,

**Comment by realcoloride** [comment]
Hey there it seems like perhaps I did a mistake. I apologize.

Placing the version header before causes corruption.
devenv_SJQuSzKQbk
Code_AQo5TEEoU1

I'm again sorry, I should have double checked the order

**Comment by realcoloride** [comment]
This should fix it https://github.com/realcoloride/WebSocket4Net/commit/ecdb753d7c729fdefc369df72621d74ddceb379f

**Comment by realcoloride** [comment]
This should fix it https://github.com/realcoloride/WebSocket4Net/commit/ecdb753d7c729fdefc369df72621d74ddceb379f
@kerryjiang

**Pull request merged**
