### PR TITLE
Support for TLS 1.1 & TLS 1.2

### PR DESCRIPTION
**Pull request by jchapuis**
Updated SuperSocket.ClientEngine with version supporting list of enabled Ssl Protocols. WebSocket constructors now include list of enabled Ssl Procotols parameter.

### CODE REVIEW

**Comment by kerryjiang** [comment]
Can we simplify the change by setting the enabledSslProtocols with "SslProtocols.Ssl3 | SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12"?

**Comment by jchapuis** [comment]
Hi Kerry! First of all thanks a lot for your answer and your work!

Yes sure good idea, in our case for instance the server chooses the protocol so it’s fine.

Thanks again!

Cheers,

Jonas

**Comment by kerryjiang** [comment]
Actually I am not sure whether they can work together correctly. Because I read the code of BCL about that, there is a system registry key to control whether use SslProtocols.Default (Ssl3 | TLS) or SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12.

Could you try this for me?

private SslProtocols DefaultProtocols()
{
	SslProtocols result = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;
	if (ServicePointManager.DisableStrongCrypto)
	{
		result = SslProtocols.Default;
	}
	return result;
}

**Comment by jchapuis** [comment]
Hi Kerry,

So I checked and passing SslProtocols.Ssl3 | SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 works like a charm with our server which only accepts TLS1.2

It’s interesting because that DefaultProcotols() method seems to exist only in more recent versions of the framework, in the 4.0 version it’s using SslProcotols.Default

For us the registry key is actually not an option for a question of predictability and security (sorry I haven’t tried it though). There’s also System.Net.ServicePointManager.SecurityProtocol but this one doesn’t seem to be used by SslStream, only TlsStream. I actually tried setting it to SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 before instantiating the WebSocket but it doesn’t work. If it could work that would be an acceptable solution for us though, because it’s an application-wide setting. So one way could be to just pick the value from there for your default, like they do in TlsStream.

This whole stuff is quite messy I have to say ☺ it would require more investigation but it’s getting quite late here ;)

Thanks

Jonas

**Pull request closed without merging**
